## The below comment applies to the generated source, not to this Mako template.
// Autogenerated -- Do not edit!
// Origin: pygments.token.
// Generated by extract.py for Jgments:
//   http://s/?fileprint=//depot/google3/third_party/java_src/java/com/google/jgments/extract.py.

package ${package};

public enum Token {
  % for token in tokens[:-1]:
    ${token},
  % endfor
    ${tokens[-1]};
}
